### ISSUE TITLE
The  public function name  `Manuel` is spelled incorrectly

### ISSUE THREAD

**Issue by nisrulz** [lyrebirdstudio/Croppy#4]
Here is the function in source code: https://github.com/lyrebirdstudio/Croppy/blob/0bd49dfa62b4b2e770cb2efc499f6ee625842ee8/croppylib/src/main/java/com/lyrebirdstudio/croppylib/main/CropRequest.kt#L18

I believe it was meant to be [`Manual`](https://www.dictionary.com/browse/manual).

I don't thing it is a problem, but the meaning implied is incorrect. This is also referenced in the Readme file.

**Comment by iammert** [comment]
Fixed 👍
